export function add(...values: any[]): number;
export function minus(...values: any[]): number;
export function divide(...values: any[]): number;
export function multiply(...values: any[]): number;
export function mean(...values: any[]): number;
export function median(...values: any[]): number;
export function mode(...values: any[]): number;
export function range(...values: any[]): number;
export function percent(value: any): number;
export function power(value: any, exponent?: any): number;
export function reciprocal(value: any): number;
export function square(value: any): number;
export function sqrt(value: any): number;
